export const UPDATE_GROUP_SEARCH = 'UPDATE_GROUP_SEARCH'
export const UPDATE_USER_SEARCH = 'UPDATE_USER_SEARCH'
export const UPDATE_TASKS_SEARCH = 'UPDATE_TASKS_SEARCH'
export const UPDATE_EVENTS_SEARCH = 'UPDATE_EVENTS_SEARCH'
export const UPDATE_DEADLINES_SEARCH = 'UPDATE_DEADLINES_SEARCH'

